import {
  Folder,
  FolderOpen,
  Code,
  Code2,
  BookOpen,
  BookMarked,
  Briefcase,
  Home,
  Star,
  Rocket,
  ShoppingCart,
  Wrench,
  Heart,
  Globe,
  Lightbulb,
  Camera,
  Music,
  Film,
  Gamepad2,
  Plane,
  Car,
  Bike,
  Dumbbell,
  Coffee,
  Pizza,
  Leaf,
  Flower2,
  Sun,
  Moon,
  Zap,
  Target,
  Trophy,
  GraduationCap,
  Microscope,
  Palette,
  PenTool,
  Megaphone,
  Users,
  Building,
  Map,
  Database,
  Server,
  Terminal,
  Cpu,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface PresetIcon {
  name: string;
  icon: LucideIcon;
}

export const PRESET_ICONS: PresetIcon[] = [
  // Files & Work
  { name: "Folder", icon: Folder },
  { name: "FolderOpen", icon: FolderOpen },
  { name: "Briefcase", icon: Briefcase },
  { name: "Building", icon: Building },
  { name: "Target", icon: Target },
  { name: "Trophy", icon: Trophy },
  // Code & Tech
  { name: "Code", icon: Code },
  { name: "Code2", icon: Code2 },
  { name: "Terminal", icon: Terminal },
  { name: "Database", icon: Database },
  { name: "Server", icon: Server },
  { name: "Cpu", icon: Cpu },
  // Learning
  { name: "BookOpen", icon: BookOpen },
  { name: "BookMarked", icon: BookMarked },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Microscope", icon: Microscope },
  { name: "Lightbulb", icon: Lightbulb },
  // Creative
  { name: "Palette", icon: Palette },
  { name: "PenTool", icon: PenTool },
  { name: "Camera", icon: Camera },
  { name: "Music", icon: Music },
  { name: "Film", icon: Film },
  { name: "Megaphone", icon: Megaphone },
  // Life & Hobbies
  { name: "Home", icon: Home },
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Rocket", icon: Rocket },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Bike", icon: Bike },
  // Travel & Nature
  { name: "Globe", icon: Globe },
  { name: "Plane", icon: Plane },
  { name: "Car", icon: Car },
  { name: "Map", icon: Map },
  { name: "Leaf", icon: Leaf },
  { name: "Flower2", icon: Flower2 },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  // Misc
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Coffee", icon: Coffee },
  { name: "Pizza", icon: Pizza },
  { name: "Wrench", icon: Wrench },
  { name: "Zap", icon: Zap },
  { name: "Users", icon: Users },
];
